### ISSUE TITLE
error in log

### ISSUE THREAD

**Issue by MikhailY** [pillarjs/send#158]
```
RangeNotSatisfiableError: Range Not Satisfiable
    at SendStream.error (/root/front/node_modules/send/index.js:270:31)
    at SendStream.send (/root/front/node_modules/send/index.js:671:19)
    at onstat (/root/front/node_modules/send/index.js:730:10)
    at FSReqWrap.oncomplete (fs.js:171:5)
```
The error comes out in the log
version 0.16.2

**Comment by dougwilson** [comment]
Hi @MikhailY the error means that a request asked for a range that was outside the size of the file requested and so a Range Not Satisfiable had to be sent back as the response to that request as per HTTP specification. 👍
