### ISSUE TITLE
Tests error

### ISSUE THREAD

**Issue by guimard** [pillarjs/send#178]
Hello,

I've this error with tests:
```
  60 passing (395ms)
  1 failing

  1) send(file).pipe(res)
       with Range request
         when multiple ranges
           should respond with 206 is all ranges can be combined:
     Error: expected '23456' response body, got '123456789'
      at error (/usr/lib/nodejs/supertest/lib/test.js:235:13)
      at Test.assert (/usr/lib/nodejs/supertest/lib/test.js:180:21)
      at Server.assert (/usr/lib/nodejs/supertest/lib/test.js:132:12)
      at emitCloseNT (net.js:1629:8)
      at process._tickCallback (internal/process/next_tick.js:63:19)
```
Cheers,
Xavier

**Comment by dougwilson** [comment]
Hi! I just tried the tests and, just like our CI, they all pass. Looking at the test, the only thing that jumps out at me as to what the issue may be is that you have an incompatible version of the "range-parser" module installed somehow. This module requires version 1.2.0 or higher of that module. What version do you have installed of "range-parser"?

**Comment by guimard** [comment]
Hello,
even with a fresh install (`npm install`), a new failure is back:
```
  150 passing (517ms)
  1 failing

  1) send.mime
       .default_type
         should change the default type:
     Error: expected "Content-Type" header field
      at Test._assertHeader (node_modules/supertest/lib/test.js:209:30)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1629:8)
      at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by dougwilson** [comment]
I can't reproduce. Can you provide instructions to reproduce or a patch?

**Comment by guimard** [comment]
Sorry, was with a previous version.
