### ISSUE TITLE
Send breaks jest

### ISSUE THREAD

**Issue by parkan** [pillarjs/send#83]
Looks like trying to require express, which requires send, breaks jest mock generation:

```
> mine-relay-server@1.0.0 test /Users/arkadiy/mine/mine-relay-server
> BABEL_JEST_STAGE=1 jest

Using Jest CLI v0.5.10
 FAIL  __tests__/jwt.js (1.496s)
● createToken › it encountered a declaration exception
  - TypeError: /Users/arkadiy/mine/mine-relay-server/server/routers/jwt.js: /Users/arkadiy/mine/mine-relay-server/node_modules/express/index.js: /Users/arkadiy/mine/mine-relay-server/node_modules/express/lib/express.js: /Users/arkadiy/mine/mine-relay-server/node_modules/express/lib/application.js: /Users/arkadiy/mine/mine-relay-server/node_modules/express/lib/view.js: /Users/arkadiy/mine/mine-relay-server/node_modules/express/lib/utils.js: /Users/arkadiy/mine/mine-relay-server/node_modules/send/index.js: Cannot read property 'function' of undefined
        at Object.<anonymous> (node_modules/send/index.js:156:38)
        at Object.runContentWithLocalBindings (node_modules/jest-cli/src/lib/utils.js:527:17)
        at Loader._execModule (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:239:9)
        at Loader.requireModule (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:902:12)
        at Loader._generateMock (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:270:30)
        at Loader.requireMock (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:798:43)
        at Loader.requireModuleOrMock (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:921:17)
        at Object.<anonymous> (node_modules/express/lib/utils.js:19:12)
        at Object.runContentWithLocalBindings (node_modules/jest-cli/src/lib/utils.js:527:17)
        at Loader._execModule (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:239:9)
        at Loader.requireModule (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:902:12)
        at Loader._generateMock (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:270:30)
        at Loader.requireMock (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:798:43)
        at Loader.requireModuleOrMock (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:921:17)
        at Object.<anonymous> (node_modules/express/lib/view.js:19:13)
        at Object.runContentWithLocalBindings (node_modules/jest-cli/src/lib/utils.js:527:17)
        at Loader._execModule (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:239:9)
        at Loader.requireModule (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:902:12)
        at Loader._generateMock (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:270:30)
        at Loader.requireMock (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:798:43)
        at Loader.requireModuleOrMock (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:921:17)
        at Object.<anonymous> (node_modules/express/lib/application.js:22:12)
        at Object.runContentWithLocalBindings (node_modules/jest-cli/src/lib/utils.js:527:17)
        at Loader._execModule (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:239:9)
        at Loader.requireModule (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:902:12)
        at Loader._generateMock (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:270:30)
        at Loader.requireMock (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:798:43)
        at Loader.requireModuleOrMock (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:921:17)
        at Object.<anonymous> (node_modules/express/lib/express.js:17:13)
        at Object.runContentWithLocalBindings (node_modules/jest-cli/src/lib/utils.js:527:17)
        at Loader._execModule (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:239:9)
        at Loader.requireModule (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:902:12)
        at Loader._generateMock (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:270:30)
        at Loader.requireMock (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:798:43)
        at Loader.requireModuleOrMock (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:921:17)
        at Object.<anonymous> (node_modules/express/index.js:11:18)
        at Object.runContentWithLocalBindings (node_modules/jest-cli/src/lib/utils.js:527:17)
        at Loader._execModule (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:239:9)
        at Loader.requireModule (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:902:12)
        at Loader._generateMock (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:270:30)
        at Loader.requireMock (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:798:43)
        at Loader.requireModuleOrMock (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:921:17)
        at Object.<anonymous> (server/routers/jwt.js:4:111)
        at Object.runContentWithLocalBindings (node_modules/jest-cli/src/lib/utils.js:527:17)
        at Loader._execModule (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:239:9)
        at Loader.requireModule (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:902:12)
        at Loader.requireModuleOrMock (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:923:17)
        at Suite.<anonymous> (__tests__/jwt.js:4:3)
        at env.describe_ (evalmachine.<anonymous>:40:25)
        at env.describe (evalmachine.<anonymous>:27:19)
        at Object.<anonymous> (__tests__/jwt.js:3:1)
        at Object.runContentWithLocalBindings (node_modules/jest-cli/src/lib/utils.js:527:17)
        at Loader._execModule (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:239:9)
        at Loader.requireModule (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:902:12)
        at jasmineTestRunner (node_modules/jest-cli/src/jasmineTestRunner/jasmineTestRunner.js:284:16)
        at node_modules/jest-cli/src/TestRunner.js:379:12
        at process._tickCallback (node.js:356:9)
1 test failed, 0 tests passed (1 total)
Run time: 2.294s
npm ERR! Test failed.  See above for more details.
```

I'm not entirely sure how to approach this.

**Comment by dougwilson** [comment]
No idea either. Any way to provide me with instructions on how I can reproduce?

**Comment by parkan** [comment]
```
git clone git@github.com:parkan/send-jest.git
npm install
npm test
```

You should see:

```
> send-jest@1.0.0 test /private/tmp/send-jest
> jest

Using Jest CLI v0.5.10
 FAIL  __tests__/send.js (0.129s)
● send › it does not work
  - TypeError: /private/tmp/send-jest/node_modules/send/index.js: Cannot read property 'function' of undefined
        at Object.<anonymous> (node_modules/send/index.js:156:38)
        at Object.runContentWithLocalBindings (node_modules/jest-cli/src/lib/utils.js:527:17)
        at Loader._execModule (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:239:9)
        at Loader.requireModule (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:902:12)
        at Loader._generateMock (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:270:30)
        at Loader.requireMock (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:798:43)
        at Loader.requireModuleOrMock (node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:921:17)
        at Spec.<anonymous> (__tests__/send.js:3:9)
1 test failed, 0 tests passed (1 total)
Run time: 0.575s
npm ERR! Test failed.  See above for more details.
```

**Comment by dougwilson** [comment]
Ok. Is there a specific version of Node.js I need to use to reproduce? Running in Node.js 0.10 gives a syntax error.

**Comment by parkan** [comment]
Ah sorry here are the engine versions:

```
% node --version              (arkadiy@helium:..ine/mine-tristero/)
v4.1.1
% npm --version               (arkadiy@helium:..ine/mine-tristero/)
3.3.4
```

**Comment by dougwilson** [comment]
Ok, it looks like there is some really, really magical something going on with whatever this jest thing is. For example, the `require('depd')` returns some weird mocked thing and `console.dir(require('depd').toString())` results in `'function depd(){return mockConstructor.apply(this,arguments);}'`, which is not what the source code for that library is.

Then when I call `require('depd')('test')`, `undefined` is returned instead of the expected function.

**Comment by dougwilson** [comment]
From what I read from http://facebook.github.io/jest/docs/api.html, you're not completely using the `jest` API; you need to either mock the `depd` module or mark the `depd` module are "do not mock":

Adding the following at the top of your tests fixes the issue: `jest.dontMock('depd')`. If you don't want to do this, then you'll have to actually implement the mock.

**Comment by parkan** [comment]
Good call, I tried not mocking `send` itself but that didn't help. `jest.dontMock('depd');` works. Thank you!
